export const KANTO = "関東"
export const TOKYO = "東京"
export const KANAGAWA = "神奈川"
export const SAITAMA = "埼玉"
export const CHIBA = "千葉"
export const IBARAKI = "茨城"
export const TOCHIGI = "栃木"
export const GUNMA = "群馬"
export const YAMANASHI = "山梨"
export const NAGANO = "長野"

export const KANSAI = "関西"
export const OSAKA = "大阪"
export const KYOTO = "京都"
export const HYOGO = "兵庫"
export const NARA = "奈良"
export const WAKAYAMA = "和歌山"
export const SHIGA = "滋賀"